dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: bBL9c6GgAOxVyNFGCDbUGh3M5itlsYUnXnluaZ+mAVOR2cKanqFn7AatGA2utKk4Wc8SW3BYahsAxAeJO1iXL52dAww40gxKjHgKED/uH+MTYEhjryHiKMuRwMqdyfgT/vbpj9HJtpmhl/wCc8OW3WINGrP8hoU669IjMpJTkB5MPSl5dUY6KLElsAw/UyuNdv2vg8DgMPZFPyCVt6dA94M0Cpa0pNvsnuk0MmWfvJAgPOinw7y50ZV7ruTYmpXj5ok+06Z2oC+Mwpvc8w85I9ikqNCB8am64QVvYxTXfZ4tR6H1t4AgCXa2p+F8xG+L2WoVcIggN832c+7Cl+LuNNN9T1Ab8w5hXw78qJcHJDP+ZT55XYXqjadbjPyYsKV5l2Hz/wKOoawP7E9O60dIspZdaOAf+cLBIXafKeQ+D5zI4BgxLl8/keYMlWvLjOdJE793BQHBg8QuIg63baJRDEgOWdjnlt/nrij+YIqP62oD2GOqoBqY89V/5w+JRuzgkuTvaoA12e165d10we6ZCo7ZCoFmkcUR610T68QpCgcwhQ59K+asqdyTlnjwctPqKl2aM7CbbLpGsMBGVXHoOZjoCsNquAiPPgdubYb12W8D172h3xJjEgwHxZOV7aj0JQ42riAMbRISILr9Qk1NNAsadk3E2WRALJzJNWrqg4E=
