---
- name: Install MongoDB 4.0
  hosts: all
  become: true
  tasks:

  - name: Update repositories cache
    apt: update_cache=yes force_apt_get=yes

  - name: Upgrading all apt packages
    apt: upgrade=dist force_apt_get=yes

  # Добавим ключ репозитория для последующей работы с ним
  - name: Add APT key
    apt_key:
      id: E52529D4
      keyserver: keyserver.ubuntu.com

  # Подключаем репозиторий с пакетами mongodb
  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
      state: present

  # Выполним установку пакета
  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present

  # Включаем сервис
  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
